export const tableHeads = [
    { hasIcon: "N", text: "Drug" },
    { hasIcon: "N", text: "Event" },
    { hasIcon: "Y", text: "Status" },
    { hasIcon: "Y", text: "Alerts" },
    { hasIcon: "Y", text: "Fatal Since 2022 Q1" },
    { hasIcon: "Y", text: "Fatal Since 2022 Q2" },
    { hasIcon: "Y", text: "Comments" },
  ];

export const tableValues = [
    {
      drug: "Paracetomol",
      event: "Diarrhea",
      status: "Active",
      alerts: ["F", "D", "I"],
      fatal_2022_q1: 13,
      fatal_2022_q2: 212,
      comments: "Pending further info",
    },
    {
      drug: "Paracetomol",
      event: "Diarrhea",
      status: "Active",
      alerts: ["F", "I"],
      fatal_2022_q1: 10,
      fatal_2022_q2: 221,
      comments: "Of Note",
    },
    {
      drug: "Paracetomol",
      event: "Diarrhea",
      status: "Active",
      alerts: ["F", "I"],
      fatal_2022_q1: 10,
      fatal_2022_q2: 1133,
      comments: "Pending further info",
    },
    {
      drug: "Paracetomol",
      event: "Diarrhea",
      status: "Active",
      alerts: ["F", "D", "I"],
      fatal_2022_q1: 9,
      fatal_2022_q2: 133,
      comments: "Of Note",
    },
    {
      drug: "Paracetomol",
      event: "Diarrhea",
      status: "Active",
      alerts: ["F", "I"],
      fatal_2022_q1: 7,
      fatal_2022_q2: 82,
      comments: "Of Note",
    },
    {
      drug: "Paracetomol",
      event: "Diarrhea",
      status: "Active",
      alerts: ["F"],
      fatal_2022_q1: 7,
      fatal_2022_q2: 96,
      comments: "Pending further info",
    },
    {
      drug: "Paracetomol",
      event: "Diarrhea",
      status: "Active",
      alerts: ["F"],
      fatal_2022_q1: 5,
      fatal_2022_q2: 89,
      comments: "Pending further info",
    },
  ];